---
- hosts: all
  become: yes
  tasks:
  - name: install jdk8 on ubuntu20 node1
    apt:
     name: openjdk-8-jre
     state: present
    when: ansible_os_family == "Debian"

  - name: install jdk8 on amazonlinux2 node2
    yum:
     name: java-1.8.0-openjdk
     state: present
    when: ansible_os_family == "RedHat"